### ISSUE TITLE
Add reason for being unmaintained

### ISSUE THREAD

**Issue by stephenh** [GeekyAnts/mobx-state-tree-firebase#11]
Hi; I just came across this project. Understood it's unmaintained, if you don't mind, could you add a small blurb about why to the readme? E.g. I'm primarily interested if:

a) is this unmaintained b/c the approach didn't work out and is fundamentally flawed?
b) is this unmaintained b/c there is another library that does the same thing but better, if so what?
c) is this unmaintained solely b/c the author doesn't have time/moved on to other technologies, but the existing code might be worth using+updating? 

Thanks!

**Comment by sanketsahu** [comment]
a) is this unmaintained b/c the approach didn't work out and is fundamentally flawed?
> It worked well

b) is this unmaintained b/c there is another library that does the same thing but better, if so what?
> Not really

c) is this unmaintained solely b/c the author doesn't have time/moved on to other technologies, but the existing code might be worth using+updating?
> Yes, I don't have time to maintain it.

**Comment by stephenh** [comment]
Cool, thanks!

**Comment by corysimmons** [comment]
@sanketsahusoft Very cool project and thanks for updating us on whether the approach worked well or was flawed. 👌I might take a stab at something similar soon.
