### ISSUE TITLE
Typescript model types?

### ISSUE THREAD

**Issue by Spiralis** [GeekyAnts/mobx-state-tree-firebase#6]
I see that the type is lost with the FirebaseModel construct. When I call `actions( self => ...` then the self variable is `any`. 

Any plans on defining types for this so that the object structure declared in the props method keeps it's original types?

**Comment by Spiralis** [comment]
Hi again,

I had a chance to look at this again today. 
I am having a problem when I import it from npm (no default firebase app setup). So, for testing and tuning this I instead embedded the mobx-state-tree-firebase index file into my test-project. I also prepended the file with my firebase-config. Then it started behaving. Not sure why I had to do this though.

In any case, I then started to try to preserve the typescript types that the mst project provides. I did a couple of minor changes;

1. I first removed the `: any` from the FirebaseModel construct:
```
export const FirebaseModel = types
    .model( ...
```
This should allow Typescript to infer the type from the `mst` types from the `types.model()`call instead.

2. Since my tslint is set to disallow object access via string literals I then changed the `const _getDatabase` function to also take `any` and changed to not use "array" access for the `properties`:
```
const _getDatabase = function(Model: typeof FirebaseModel | any) {
    const path = Model.properties._path.defaultValue;
    return firebase.database().ref(path);
};
```
Now, this is far from ideal. But, with my limited typescript knowledge, I was not able to quickly come up with a solution.

After this things looks better.


I do still have an issue in constructing the props for my react components though:
If I have a Post model defined as follows: 
```
import { FirebaseModel } from '../mobx-state-tree-firebase';
import { types, getSnapshot, getType } from "mobx-state-tree";

const Post = FirebaseModel.named("Post")
.props({
  _path: "posts",
  title: types.string,
  description: types.string
})
.actions((self) => {
  return {
    updateTitle(newTitle: string) {
      self.title = newTitle;
    },
  };
});

export default Post
```

And, I then try to use it like this:
```
import * as React from 'react'
import { observer } from "mobx-react"
import Post from './models/Post'

interface AppProps {
  post: typeof Post
}
class App extends React.Component<AppProps , any> {
  render() {
    return (
      <div className="App">
          Post title: "{this.props.post.title}"
      </div>
    );
  }
}

export default observer(App)
```
Then the `title` prop is not recognized. Although, in VS Code the tooltip does show the type props, but still with a squiggly:
![image](https://user-images.githubusercontent.com/64342/32414849-8be468d8-c22f-11e7-9ebd-907ca8e1486d.png)


And the main page that tries to use App complaints about:
```
(19,8): error TS2322: Type '{ post: { _id: string; _path: string; } & { save(): Promise<any>; } & { _path: string; title: str...' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<App> & Readonly<{ children?: ReactNode; }> & Reado...'.
  Type '{ post: { _id: string; _path: string; } & { save(): Promise<any>; } & { _path: string; title: str...' is not assignable to type 'Readonly<AppProps>'.
    Types of property 'post' are incompatible.
      Type '{ _id: string; _path: string; } & { save(): Promise<any>; } & { _path: string; title: string; des...' is not assignable to type 'IModelType<{ _id?: any; _path?: any; } & Snapshot<{ _path: string; title: string; description: st...'.
```
![image](https://user-images.githubusercontent.com/64342/32414858-a5fc4358-c22f-11e7-9d96-8720cab59270.png)

I am able to get around this error and get the test-app working by just setting post to be of type `any` , but that is really not ideal in regards to using Typescripts featureset.

Any ideas?

**Comment by sanketsahu** [comment]
@Spiralis Thanks for following up on this. I am not really sure about this particular use-case.

But, we are actually re-writing this library with Firestore instead of Firebase Realtime Database. So, things will change.

**Comment by Spiralis** [comment]
I see. Hm. I have been looking at Firestore, but I found the business model for my use-case to be a worse fit. Firebase will probably be cheaper for me, as my database will have a low amount of data in it, but instead more often accessed. Happy to see your experiment here anyway :)

**Comment by SupriyaKalghatgi** [comment]
@Spiralis https://github.com/GeekyAnts/firestore-react

**Comment by sanketsahu** [comment]
@SupriyaKalghatgi @Spiralis That's the one with Firestore + React only with no MST.

We are working on Firestore + React + MST. Also, evaluating Apollo Client (if that fits well).

**Comment by Spiralis** [comment]
Yeah. Thanks  @SupriyaKalghatgi . But, what I am interested in is Firebase + React + MST.

**Comment by Spiralis** [comment]
BTW: I got the typings fixed. I had missed a chapter in MST regarding this topic. The solution is to set the props for the react container to `type AppProps = typeof Post.Type`, if I recall correctly.

**Comment by joshua1** [comment]
@sanketsahusoft how do i access the Firestore + MST module. Thanks
