### ISSUE TITLE
Issue running `npm run build`

### ISSUE THREAD

**Issue by Spiralis** [GeekyAnts/mobx-state-tree-firebase#7]
When I run the build command as given in the title, I am getting an issue with the minification. The project was created using create-react-app with typescript: `create-react-app mst-todo --scripts-version=react-scripts-ts`
 
```
npm run-script build

> mst-todo@0.1.0 build D:\src\INTS\mst-todo
> react-scripts-ts build

Creating an optimized production build...
Warning: The 'no-use-before-declare' rule requires type information.
ts-loader: Using typescript@2.5.3 and D:\src\INTS\mst-todo\tsconfig.json
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/mobx-state-tree-firebase/dist/index.js:11
```

Any ideas?

**Comment by Spiralis** [comment]
When I run the same command using yarn, it also fails, but yarn gives an additional help-link: http://bit.ly/2tRViJ9:

>You may occasionally find a package you depend on needs compiled or ships code for a non-browser environment.
>This is considered poor practice in the ecosystem and does not have an escape hatch in Create React App.
>
>To resolve this:
>
>Open an issue on the dependency's issue tracker and ask that the package be published pre-compiled (retaining ES6 Modules).
>Fork the package and publish a corrected version yourself.
>If the dependency is small enough, copy it to your src/ folder and treat it as application code.

**Comment by sanketsahu** [comment]
I think changing to ES6 would solve it so going to close this one.
