### ISSUE TITLE
Problem initializing firebase "... No Firebase App '[DEFAULT]' has been created ..."

### ISSUE THREAD

**Issue by Spiralis** [GeekyAnts/mobx-state-tree-firebase#9]
```
Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app).
```

This happens on line 5 of the `dist/index.js` file. Note though that this is with my modified index.js (ref PR #8. But, I believe that it probably happens with the old version too, I just wasn't able to get this far with the original.

**Comment by sanketsahu** [comment]
You need to create a config file for Firebase initialization and import it before you import this library.

On a side note, this library is a work-in-progress at the moment. But you can give it a shot.

**Comment by Spiralis** [comment]
Cool. I understand that it is WIP :). I just had to give it a shot, it seemed like it could make life a lot easier for me :). 
BTW: I did actually make a config and ran the firebase initialize method, but somehow it still complained. Not sure why.
